### ISSUE TITLE
Unintuitive shortcut placement

### ISSUE THREAD

**Issue by avin-kavish** [curveball/core#134]
Why am I setting the response status code on the `ctx` object but the response body at `ctx.response`? Feels a bit awkward.

```
  ctx.status = 200;
  ctx.response.body = 'Hello world!'
```

**Comment by evert** [comment]
The status on `ctx` is a shortcut for `ctx.response.status` (which also works). 

The reason that some some of these properties are available on the Context object, but some aren't is because only the unambiguous  appear.

That basically excludes `body`, `header`, `type` and a few others. All of those exist on _both_ the request and the response.

**Comment by avin-kavish** [comment]
That's not very intuitive...

**Comment by evert** [comment]
Makes sense, but this is unlikely to change at this point. I added the shortcuts to give some familiarity to Koa users, but even then felt it was a bit unneeded. Renaming request/response to req/res to save a few characters is not really a high enough priority.
